package pacificsoft.pscomandera.serviciosweb;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.2
//
// Created by Quasar Development
//
//---------------------------------------------------


import android.os.StrictMode;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.Transport;

import java.util.List;

import pacificsoft.pscomandera.Modelo.Movimiento;


public class AMTBasicHttpBinding_IService
{
    interface AMTIWcfMethod
    {
        AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url;//"http://ps-pruebas.cloudapp.net/VP/Service.svc";

    int timeOut=80000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    AMTIServiceEvents callback;
    public AMTBasicHttpBinding_IService(){
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();

        StrictMode.setThreadPolicy(policy);

    }
    public AMTBasicHttpBinding_IService(String url){
        setUrl( url );
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);

    }

    public AMTBasicHttpBinding_IService (AMTIServiceEvents callback)
    {
        this.callback = callback;
    }
    public AMTBasicHttpBinding_IService(AMTIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public AMTBasicHttpBinding_IService(AMTIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(getUrl());
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(getUrl(),timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
            e.printStackTrace();
        }
        return null;
    }

    protected AMTExtendedSoapSerializationEnvelope createEnvelope()
    {
        AMTExtendedSoapSerializationEnvelope envelope= new AMTExtendedSoapSerializationEnvelope(AMTExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }

    protected List sendRequest(String methodName,AMTExtendedSoapSerializationEnvelope envelope,Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    Object getResult(Class destObj,Object source,String resultName,AMTExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }


    public String Login(final String usuario,final String password,final String tipoVendedor ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Login");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="usuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(usuario!=null?usuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(password!=null?password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="tipoVendedor";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(tipoVendedor!=null?tipoVendedor:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("LoginResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/Login",__profile);
    }

    public String Validar() throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Validar");
                __envelope.setOutputSoapObject(__soapReq);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ValidarResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/Validar",__profile);
    }

    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> LoginAsync(final String usuario,final String password,final String tipoVendedor)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return Login( usuario,password,tipoVendedor);
            }
        },"Login");
    }

    public String ListaVendedores(final int tipo ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListaVendedores");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="tipo";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(tipo>0?tipo:0);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ListaVendedoresResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/ListaVendedores",__profile);
    }




    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> ListaVendedoresAsync(final int tipo)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return ListaVendedores(tipo);
            }
        },"ListaVendedores");
    }

    public String CajasEntrar(final String idCaja ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CajasEntrar");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idCaja";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idCaja!=null?idCaja:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("CajasEntrarResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/CajasEntrar",__profile);
    }

    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> CajasEntrarAsync(final String idCaja)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CajasEntrar( idCaja);
            }
        },"CajasEntrar");
    }

    public String CajasCerrar(final String idCaja ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CajasCerrar");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idCaja";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idCaja!=null?idCaja:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("CajasCerrarResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/CajasCerrar",__profile);
    }

    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> CajasCerrarAsync(final String idCaja)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CajasCerrar( idCaja);
            }
        },"CajasCerrar");
    }

    public String Articulo(final String codigo,final String almacen ) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Articulo");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="articulo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codigo!=null?codigo:null);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="almacen";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(almacen!=null?almacen:null);
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ArticuloResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/Articulo",__profile);
    }




    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> ArticuloAsync(final String articulo,final String almacen)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return Articulo( articulo,almacen);
            }
        },"Articulo");
    }






    public String Cajas( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Cajas");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("CajasResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/Cajas",__profile);
    }

    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> CajasAsync()
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return Cajas( );
            }
        },"Cajas");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    //public String GuardaNotaVentaEnEspera(final String xml ) throws Exception
    //{
    //    /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
    //    throw new UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    //}

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> GuandaNotaVentaEnEsperaAsync(final String xml)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return GuardaNotaVentaEnEspera( xml);
            }
        },"GuardaNotaVentaEnEspera");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */


    public String Almacenes( ) throws Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Almacenes");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("AlmacenesResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/Almacenes",__profile);
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> AlmacenesAsync()
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return Almacenes( );
            }
        },"Almacenes");
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public String ValidaCajas(final String codigo ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ValidaCajas");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="codigo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(codigo!=null?codigo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ValidaCajasResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/ValidaCajas",__profile);
    }

    /**
     * This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
     */
    public android.os.AsyncTask< Void, Void, AMTOperationResult< String>> ValidaCajasAsync(final String codigo)
    {
        return executeAsync(new AMTFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return ValidaCajas( codigo);
            }
        },"ValidaCajas");
    }


    public String GuardaNotaVentaEnEspera(final String XMLArticulos ) throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GuardaNotaVentaEnEspera");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="xml";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(XMLArticulos!=null?XMLArticulos:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GuardaNotaVentaEnEsperaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/GuardaNotaVentaEnEspera",__profile);
    }

    public String GuardaNotaDeVenta(final String XMLArticulos ) throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GuardaNotaDeVenta");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="xml";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(XMLArticulos!=null?XMLArticulos:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GuardaNotaDeVentaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/GuardaNotaDeVenta",__profile);
    }

    public String GeneraFolioReferencia() throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GeneraFolioReferencia");
                __envelope.setOutputSoapObject(__soapReq);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GeneraFolioReferenciaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/GeneraFolioReferencia",__profile);
    }

    public String PagoNotaDeVenta(final String XMLArticulos ) throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "PagoNotaDeVenta");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="xml";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(XMLArticulos!=null?XMLArticulos:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("PagoNotaDeVentaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/PagoNotaDeVenta",__profile);
    }



    public String ValidaFolioEnEspera(final String CAJ_FOLIO) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ValidaFolioEnEspera");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="folio";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(CAJ_FOLIO!=null?CAJ_FOLIO:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ValidaFolioEnEsperaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/ValidaFolioEnEspera",__profile);
    }

    //Servicios que se ejecutan bajo la segundo
    public String GuardaInvalida(final String CAJ_FOLIO) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GuardaInvalida");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="NUM_TRANSAC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(CAJ_FOLIO!=null?CAJ_FOLIO:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GuardaInvalidaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IPSServicioMP/GuardaInvalida",__profile);
    }

    //Servicios que se ejecutan bajo la segundo
    public String DatosTerminal(final String terminal) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "DatosTerminal");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="terminal";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(terminal!=null?terminal:null);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("DatosTerminalResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IPSServicioMP/DatosTerminal",__profile);
    }

    //Servicios que se ejecutan bajo la segundo
    public String TicketCorreo(final String ticket,final String correo) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "TicketCorreo");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ticket";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ticket!=null?ticket:"");
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="correo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(correo!=null?correo:"");
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("DatosTerminalResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IPSServicioMP/DatosTerminal",__profile);
    }

    public String GuardaMovimiento(final Movimiento movimiento) throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GuardaMovimiento");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TIPO_MOVTC";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(movimiento.getTIPO_MOVTC()!=null?movimiento.getTIPO_MOVTC().toString():null);
                __soapReq.addProperty(__info);


                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TIPO_TARJETA";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getTIPO_TARJETA()!=null?movimiento.getTIPO_TARJETA().toString():"");
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="TIPO_ENTRADA";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getTIPO_ENTRADA()!=null?movimiento.getTIPO_ENTRADA().toString():"");
                __soapReq.addProperty(__info);


                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="CODIGO_CAJA";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getCODIGO_CAJA()!=null?movimiento.getCODIGO_CAJA().toString():"");
                __soapReq.addProperty(__info);


                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="NUM_TARJETA";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getNUM_TARJETA()!=null?movimiento.getNUM_TARJETA().toString():"");
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="REFER_MOVT";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getREFER_MOVT()!=null?movimiento.getREFER_MOVT().toString():"");
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FECHAHORA_TC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getFECHAHORA_TC()!=null?movimiento.getFECHAHORA_TC().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="FECHA_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getFECHA_MOVTC()!=null?movimiento.getFECHA_MOVTC().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="HORA_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getHORA_MOVTC()!=null?movimiento.getHORA_MOVTC().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="AUTORIZ_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getAUTORIZ_MOVTC()!=null?movimiento.getAUTORIZ_MOVTC():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="REFER_PS";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getREFER_PS()!=null?movimiento.getREFER_PS().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="IMPORTE_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getIMPORTE_MOVTC()!=null?movimiento.getIMPORTE_MOVTC().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="CARGO_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getCARGO_MOVTC()!=null?movimiento.getCARGO_MOVTC().toString():null);
                __soapReq.addProperty(__info);


                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="RENGLON_MOVCAJ";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getRENGLON_MOVCAJ()!=null?movimiento.getRENGLON_MOVCAJ().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ID_CLIENTE";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getID_CLIENTE()!=null?movimiento.getID_CLIENTE().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="COD_TCPROMO";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getCOD_TCPROMO()!=null?movimiento.getCOD_TCPROMO().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="APROBACION_MOV";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getAPROBACION_MOV()!=null?movimiento.getAPROBACION_MOV().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="PROPINA_MOVTC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getPROPINA_MOVTC()!=null?movimiento.getPROPINA_MOVTC().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="NUM_TERMINAL";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getNUM_TERMINAL()!=null?movimiento.getNUM_TERMINAL().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="ID_PROVEEDO";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getID_PROVEEDOR()!=null?movimiento.getID_PROVEEDOR().toString():null);
                __soapReq.addProperty(__info);



                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="NUM_TRANSAC";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(movimiento.getNUM_TRANSAC()!=null?movimiento.getNUM_TRANSAC().toString():null);
                __soapReq.addProperty(__info);
                return __envelope;

            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GuardaMovimientoResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IPSServicioMP/GuardaMovimiento",__profile);
    }


    public String GuardaAlerta(final String XMLArticulos ) throws Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "EnvioDeAlerta");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="json";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(XMLArticulos);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("EnvioDeAlertaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/EnvioDeAlerta",__profile);
    }


    public String ValidaConexionQR() throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ValidaConexionQR");
                __envelope.setOutputSoapObject(__soapReq);

                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ValidaConexionResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/ValidaConexionQR",__profile);
    }

    public String GenerarCodigoQR(final String StringArticulosQR) throws Exception
    {

        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (String)execute(new AMTIWcfMethod()
        {
            @Override
            public AMTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                AMTExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GenerarCodigoQR");
                __envelope.setOutputSoapObject(__soapReq);



                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="strQRCodeInfo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(StringArticulosQR!=null?StringArticulosQR:"");
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(AMTExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GenerarCodigoQRResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://tempuri.org/IService/GenerarCodigoQR",__profile);
    }


    protected Object execute(AMTIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        AMTExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);

        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }

    protected < T> android.os.AsyncTask< Void, Void, AMTOperationResult< T>>  executeAsync(final AMTFunctions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, AMTOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected AMTOperationResult< T> doInBackground(Void... params) {
                AMTOperationResult< T> result = new AMTOperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(AMTOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }

    protected Exception convertToException(org.ksoap2.SoapFault fault,AMTExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;

        return newException;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return url;
    }
}


